### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by missoxd** [arthurbisneto/Hibrido#1]
Boa tarde Arthur, tudo bem?

Aqui é o Misso Marchewsky da Hibrido. Prazer! 😃 

Fiquei com duas dúvidas/considerações no repositório e queria validar com você:

* A indentação da classe "ActionPredispatch" está bem estranha aqui pra mim, sabes dizer se o arquivo está formatado corretamente?
* Ainda na classe "ActionPredispatch" vi que você usou diretamente o Object Manager no corpo do método o qual normalmente [não é recomendado](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/object-manager.html#usage-rules), você teve alguma razão específica?

Abraços

**Comment by arthurbisneto** [comment]
Boa tarde Misso, tudo ótimo e você?

A indentação estava errada mesmo. Já fiz a correção e atualizei o arquivo!

Quanto ao uso direto do Object Manager, quando fiz da primeira vez, manualmente, havia ocorrido alguns erros e acabei usando um exemplo (errado por sinal) do uso do método getRemoteAddress. Após compreender melhor a forma de programar dentro do Magento, fiz a correção do seu uso. 

Fiz as correções agora e já estão aplicadas tanto no arquivo ActionPredispatch.php quanto no pacote Hibrido.zip.

Abraços

**Comment by arthurbisneto** [comment]
Boa tarde Misso, tudo ótimo e você?

A indentação estava errada mesmo. Já fiz a correção e atualizei o arquivo!

Quanto ao uso direto do Object Manager, quando fiz da primeira vez,
manualmente, havia ocorrido alguns erros e acabei usando um exemplo (errado
por sinal) do uso do método getRemoteAddress. Após compreender melhor a
forma de programar dentro do Magento, fiz a correção do seu uso.

Fiz as correções agora e já estão aplicadas tanto no arquivo
ActionPredispatch.php quanto no pacote Hibrido.zip.

Abraços

Em ter, 29 de out de 2019 às 14:05, Misso Marchewsky <
notifications@github.com> escreveu:
